name: Check code quality

on: [push]

jobs:
  code-qality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install dependencies
        run: pip install pipenv && pipenv install --dev --system
      - name: Run fomatters
        run: python -m black --check . && python -m isort --check .
      - name: Run linter
        run: python -m ruff .
